import type { Card } from "../engine/types";

/** 덱 채우기용 더미 카드 ID (코스트 지불 소스). */
export const TUT_FILLER_ID = "tut_filler";

export const TUTORIAL_CARDS: Record<string, Card> = {
  tut_jab: {
    id: "tut_jab",
    name: "잽",
    cardType: "attack",
    cost: 3,
    delay: 2,
    advantage: 1,
    groundAttack: 1,
    effects: [],
    text: "빠른 지상 공격. 상대 공격을 카운터할 수 있습니다.",
    actionTag: "weak_punch",
    hitTimings: [{ frame: 1, ground: "hit_weak", airborne: "hit_weak" }],
  },
  tut_straight: {
    id: "tut_straight",
    name: "스트레이트",
    cardType: "attack",
    cost: 3,
    delay: 3,
    advantage: 0,
    groundAttack: 2,
    effects: [],
    text: "강한 지상 공격. 잽보다 느리지만 데미지가 높습니다.",
    actionTag: "strong_punch",
    hitTimings: [{ frame: 1, ground: "hit_strong", airborne: "hit_strong" }],
  },
  tut_rising: {
    id: "tut_rising",
    name: "강한 공격",
    cardType: "attack",
    cost: 5,
    delay: 4,
    advantage: 0,
    groundAttack: 5,
    effects: [],
    text: "강력한 지상 공격. 느리지만 데미지가 가장 높습니다.",
    actionTag: "rising_punch",
    hitTimings: [{ frame: 3, ground: "hit_strong", airborne: "hit_strong" }],
  },
  tut_jump: {
    id: "tut_jump",
    name: "도약",
    cardType: "skill",
    cost: 0,
    delay: 1,
    advantage: 0,
    effects: [{ type: "airborne", value: 1, target: "self" }],
    text: "자신이 공중 상태가 됩니다. 지상 공격을 회피합니다.",
  },
  tut_uppercut: {
    id: "tut_uppercut",
    name: "대공기",
    cardType: "attack",
    cost: 2,
    delay: 3,
    advantage: 0,
    groundAttack: 1,
    antiAirAttack: 2,
    effects: [{ type: "airborne", value: 2, target: "enemy" }],
    text: "지상 공격 후 도약합니다. 공중의 적에게 강한 데미지를 줍니다.",
    useCondition: "ground",
    actionTag: "rising_punch",
    hitTimings: [{ frame: 3, ground: "hit_strong", airborne: "hit_strong" }],
  },
  tut_bomb: {
    id: "tut_bomb",
    name: "폭탄",
    cardType: "attack",
    cost: 0,
    delay: 0,
    advantage: 0,
    groundAttack: 99,
    effects: [],
    text: "즉시 발동되는 초강력 공격.",
    actionTag: "strong_punch",
    hitTimings: [{ frame: 1, ground: "hit_strong", airborne: "hit_strong" }],
  },
  tut_power_strike: {
    id: "tut_power_strike",
    name: "파워 스트라이크",
    cardType: "attack",
    cost: 3,
    delay: 3,
    advantage: 0,
    groundAttack: 6,
    tags: ["power"],
    effects: [],
    text: "전사만 사용할 수 있는 강력한 지상 공격.",
    actionTag: "strong_punch",
    hitTimings: [{ frame: 1, ground: "hit_strong", airborne: "hit_strong" }],
  },
  tut_filler: {
    id: "tut_filler",
    name: "공백",
    cardType: "skill",
    cost: 0,
    delay: 99,
    advantage: 0,
    effects: [],
    text: "",
  },
};
