import type { Card } from "../engine/types";

export const TUTORIAL_CARDS: Record<string, Card> = {
  tut_jab: {
    id: "tut_jab",
    name: "잽",
    cardType: "attack",
    cost: 3,
    speed: 2,
    gain: 1,
    groundAttack: 1,
    effects: [],
    text: "빠른 지상 공격. 상대 공격을 캔슬할 수 있습니다.",
    actionTag: "weak_punch",
    hitTimings: [{ ms: 300, ground: "hit_weak", airborne: "hit_weak" }],
  },
  tut_straight: {
    id: "tut_straight",
    name: "스트레이트",
    cardType: "attack",
    cost: 3,
    speed: 3,
    gain: 0,
    groundAttack: 2,
    effects: [],
    text: "강한 지상 공격. 잽보다 느리지만 데미지가 높습니다.",
    actionTag: "strong_punch",
    hitTimings: [{ ms: 400, ground: "hit_strong", airborne: "hit_strong" }],
  },
  tut_rising: {
    id: "tut_rising",
    name: "승룡권",
    cardType: "attack",
    cost: 5,
    speed: 4,
    gain: 0,
    groundAttack: 3,
    effects: [],
    text: "강력한 지상 공격. 느리지만 데미지가 가장 높습니다.",
    actionTag: "rising_punch",
    hitTimings: [{ ms: 500, ground: "hit_strong", airborne: "hit_strong" }],
  },
  tut_jump: {
    id: "tut_jump",
    name: "도약",
    cardType: "skill",
    cost: 0,
    speed: 1,
    gain: 0,
    effects: [{ type: "airborne", value: 1, target: "self" }],
    text: "자신이 공중 상태가 됩니다. 지상 공격을 회피합니다.",
  },
  tut_uppercut: {
    id: "tut_uppercut",
    name: "어퍼컷",
    cardType: "attack",
    cost: 2,
    speed: 3,
    gain: 0,
    antiAirAttack: 2,
    effects: [],
    text: "공중의 적을 공격합니다. 지상에서만 사용 가능합니다.",
    useCondition: "ground",
    actionTag: "rising_punch",
    hitTimings: [{ ms: 400, ground: "hit_strong", airborne: "hit_strong" }],
  },
  tut_bomb: {
    id: "tut_bomb",
    name: "폭탄",
    cardType: "attack",
    cost: 0,
    speed: 0,
    gain: 0,
    groundAttack: 99,
    effects: [],
    text: "즉시 발동되는 초강력 공격.",
    actionTag: "strong_punch",
    hitTimings: [{ ms: 100, ground: "hit_strong", airborne: "hit_strong" }],
  },
  tut_filler: {
    id: "tut_filler",
    name: "공백",
    cardType: "skill",
    cost: 0,
    speed: 99,
    gain: 0,
    effects: [],
    text: "",
  },
};
